version: '2'
services:
    nginx:
      image: nginx:alpine
      ports:
        - "88:80"
      restart: always
      volumes:
        - /www/php:/var/www/html/:rw
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
        - ./conf/nginx/cert/:/etc/nginx/cert/:rw
        - ./log/nginx/:/var/log/nginx/:rw
      links:
          - php-fpm:php-fpm
    php-fpm:
        image: "${DOCKER_USER}/php-fpm:v1"
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - "9000"
        restart: always
        volumes:
            - /www/php:/var/www/html/:rw
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./conf/php/php-fpm.d/site.conf:/usr/local/etc/php-fpm.d/site.conf:rw
            - ./log/php-fpm/:/var/log/php-fpm/:rw